replicaCount: 1

serviceAccount:
  create: true
  name: ""

mongo:
  image:
    repository: melcamps/mongo
    tag: latest
frontend:
  image:
    repository: melcamps/frontend
    tag: latest
backend:
  image:
    repository: melcamps/backend
    tag: latest

service:
  backend:
    type: ClusterIP
    port: 3000
  frontend:
    type: NodePort
    port: 8080

mongodb:
  uri: mongodb://mongo:27017/tasks

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 70

ingress:
  enabled: true
  hosts:
    - host: task-manager.local
      paths:
        - /
