services:
  backend:
    image: melcamps/backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/tasks
    depends_on:
      - mongo

  frontend:
    image: melcamps/frontend
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://backend:3000
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
