apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: { { .Values.service.backend.port } }
          env:
            - name: MONGO_URL
              value: { { .Values.mongodb.uri } }
